apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ env.APP_NAME }}
spec:
  template:
    spec:
      containers:
        - name: ${{ env.APP_NAME }}
          readinessProbe:
            httpGet:
              path: /health
              port: ${{ env.APP_PORT }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ready
              port: ${{ env.APP_PORT }}
            initialDelaySeconds: 15
            periodSeconds: 30
