{
 "title": "prometheus-net1",
 "tags": [
  "prometheus-net",
  "net",
  "prometheus",
  ".net",
  ".net core"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instances",
    "label": "instances",
    "query": "label_values(http_requests_received_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Http requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(job) (increase(microsoft_aspnetcore_hosting_requests_per_second_total[$interval])/4)",
     "legendFormat": "{{job}}"
    },
    {
     "expr": " sum by(job) (increase(flask_http_request_total[$interval])/2)",
     "legendFormat": "__auto"
    },
    {
     "expr": " sum by(job) (increase(promhttp_metric_handler_requests_total[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Health Status",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "targets": [
    { "expr": "application_health_status", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Readiness Status",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 4 },
   "targets": [
    { "expr": "application_readiness_status", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Http Response time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (uri, job) (rate(http_request_duration_seconds_sum[1m]) * 1000) / sum by (uri, job) (rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum by (uri, job) (rate( flask_http_request_duration_seconds_sum [1m]) * 1000) / sum by (uri, job) (rate(flask_http_request_duration_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total known allocated memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes / 1024 / 1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_num_threads", "legendFormat": "{{job}}" },
    { "expr": "go_threads", "legendFormat": "{{job}}" }
   ]
  }
 ]
}