name: Integration Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'development'
        run: |
          echo "ERROR: You can only merge to main from development."
          exit 1
          
  run-integration-tests:
    runs-on: ubuntu-latest
    needs: check_branch
    name: Execute Integration Tests
    steps:
      - uses: actions/checkout@v3 # Check Out Code
      - uses: actions/setup-dotnet@v3 # Setup .NET Environment
        with:
          dotnet-version: 6.0.x
      - name: Restore .NET Dependencies
        run: dotnet restore ServiceTests/ServiceTests.sln
      - name: Build .NET Project
        run: dotnet build ServiceTests/ServiceTests.sln --no-restore
      - name: Run .NET Integration Tests
        run: dotnet test ServiceTests/ServiceTests.sln --no-build --verbosity normal
        env:
          AdminJWTToken: ${{ secrets.JWT_ADMIN_TEST_TOKEN }}
          ClientJWTToken: ${{ secrets.JWT_CLIENT_TEST_TOKEN }}
          ForbiddenClientJWTToken: ${{ secrets.JWT_CLIENT_FORBIDDEN_TEST_TOKEN }}
          InvalidToken: ${{secrets.JWT_INVALID_TEST_TOKEN}}

