kind: Deployment
apiVersion: apps/v1
metadata:
  name: device-microservice
  labels:
    app: device-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-microservice
  template:
    metadata:
      labels:
        app: device-microservice
        deploymentTimestamp: "${TIMESTAMP}"
    spec:
      containers:
        - name: device-microservice
          image: 'docker.io/brumarq/device-microservice:${ENVIRONMENT}'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 8181
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 8181
            initialDelaySeconds: 5
            periodSeconds: 10
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: device-microservice-hpa
spec:
 scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: device-microservice
  behavior:
    scaleDown: 
      policies: 
      - type: Pods 
        value: 4 
        periodSeconds: 60 
      - type: Percent
        value: 10 
        periodSeconds: 60
      selectPolicy: Min 
      stabilizationWindowSeconds: 300 
    scaleUp: 
      policies:
      - type: Pods
        value: 5 
        periodSeconds: 70
      - type: Percent
        value: 12 
        periodSeconds: 80
      selectPolicy: Max
      stabilizationWindowSeconds: 0
