kind: Deployment
apiVersion: apps/v1
metadata:
  name: device-metrics-orchestrator
  labels:
    app: device-metrics-orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-metrics-orchestrator
  template:
    metadata:
      labels:
        app: device-metrics-orchestrator
    spec:
      containers:
        - name: device-metrics-orchestrator
          image: 'docker.io/brumarq/device-metrics-orchestrator:latest'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: device-metrics-orchestrator-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: device-metrics-orchestrator
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

