kind: Deployment
apiVersion: apps/v1
metadata:
  name: firmware-microservice
  labels:
    app: firmware-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firmware-microservice
  template:
    metadata:
      labels:
        app: firmware-microservice
        deploymentTimestamp: "${TIMESTAMP}"
    spec:
      containers:
        - name: firmware-microservice
          image: 'docker.io/brumarq/firmware-microservice:${ENVIRONMENT}'
          resources:
            requests:
              cpu: "1m"
            limits:
              cpu: "500m"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 6969
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 6969
            initialDelaySeconds: 5
            periodSeconds: 10
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: firmware-microservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: firmware-microservice
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

