kind: Deployment
apiVersion: apps/v1
metadata:
  name: firmware-microservice
  labels:
    app: firmware-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firmware-microservice
  template:
    metadata:
      labels:
        app: firmware-microservice
    spec:
      containers:
        - name: firmware-microservice
          image: 'docker.io/brumarq/firmware-microservice:latest'
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "400m"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: firmware-microservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: firmware-microservice
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

