kind: Deployment
apiVersion: apps/v1
metadata:
  name: notifications-microservice
  labels:
    app: notifications-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-microservice
  template:
    metadata:
      labels:
        app: notifications-microservice
    spec:
      containers:
        - name: notifications-microservice
          image: "docker.io/brumarq/notifications-microservice:latest"
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 8282
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 8282
            initialDelaySeconds: 5
            periodSeconds: 10
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: notifications-microservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notifications-microservice
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
